import type { Metadata } from 'next'
import { Inter, Roboto_Mono } from 'next/font/google'
import './globals.css'
import { CommandBar } from '@/components/CommandBar/CommandBar'

const inter = Inter({ subsets: ['latin'], variable: '--font-inter' })
const roboto_mono = Roboto_Mono({
  subsets: ['latin'],
  variable: '--font-roboto_mono'
})

export const metadata: Metadata = {
  title: 'Is Space'
  // description: 'Generated by create next app'
}

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang='pt-BR'>
      <body className={`${inter.className} ${roboto_mono} flex`}>
        <CommandBar key={'sd'} />
        {children}
      </body>
    </html>
  )
}
